[general]

caption_extension = ".txt"
batch_size = 1
num_repeats = 1
enable_bucket = true 
bucket_no_upscale = false

[[datasets]]

image_directory = "C:/AI/musubi-tuner/source_data/goth-girls-wan2.2"
cache_directory = "C:/AI/musubi-tuner/source_data/goth-girls-wan2.2/cache"
resolution = [200,200]